from django.urls import path
from .views import (
    ApplyVoucherAPIView,
    ConfirmVoucherUsageAPIView,
    CreateVoucherAPIView,
    DistributeVoucherAPIView,
    CreateAndDistributeVoucherAPIView,
    EligibleUsersForVoucherAPIView,
    ProcessOrderSuccessEventAPIView,
    VoucherDetailAPIView,
    VoucherRecipientListAPIView,
    VoucherRecipientPageView,
    VoucherStatsOverviewAPIView,
    VoucherStatsOverviewPublicAPIView,
    VoucherPerformanceAPIView,
    VoucherRevenueChartAPIView,
    VoucherTopStatsAPIView,
    VoucherListAPIView,
    VoucherRecipientDeleteAPIView,
    UserVoucherHistoryAPIView,
)

from .delivery_views import (
    VoucherDeliveryLogAPIView,
    ResendVoucherEmailAPIView,
    SendVoucherToEmailAPIView,
)

urlpatterns = [
    path("", VoucherListAPIView.as_view()),
    path("create/", CreateVoucherAPIView.as_view()),
    path("<int:voucher_id>/", VoucherDetailAPIView.as_view()),
    path("create-and-distribute/", CreateAndDistributeVoucherAPIView.as_view()),
    path("distribute/", DistributeVoucherAPIView.as_view()),
    path("events/order-success/", ProcessOrderSuccessEventAPIView.as_view()),
    path("<int:voucher_id>/eligible-users/", EligibleUsersForVoucherAPIView.as_view()),
    path("<int:voucher_id>/recipients/", VoucherRecipientListAPIView.as_view()),
    path("<int:voucher_id>/recipients/page/", VoucherRecipientPageView.as_view()),
    path("<int:voucher_id>/recipients/<int:user_id>/", VoucherRecipientDeleteAPIView.as_view()),
    path("<int:voucher_id>/delivery-logs/", VoucherDeliveryLogAPIView.as_view()),
    path("<int:voucher_id>/resend-email/", ResendVoucherEmailAPIView.as_view()),
    path("<int:voucher_id>/send-email/", SendVoucherToEmailAPIView.as_view()),
    path("stats/overview/", VoucherStatsOverviewAPIView.as_view()),
    path("stats/overview/public/", VoucherStatsOverviewPublicAPIView.as_view()),
    path("stats/performance/", VoucherPerformanceAPIView.as_view()),
    path("stats/revenue-chart/", VoucherRevenueChartAPIView.as_view()),
    path("stats/top-vouchers/", VoucherTopStatsAPIView.as_view()),
    path("apply/", ApplyVoucherAPIView.as_view()),
    path("confirm/", ConfirmVoucherUsageAPIView.as_view()),
    path("user/<int:user_id>/history/", UserVoucherHistoryAPIView.as_view()),
]
