# Generated by Django 5.1.7 on 2026-02-22 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.FloatField()),
                ('expiry_date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('used_count', models.IntegerField(default=0)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher')),
            ],
            options={
                'unique_together': {('user', 'voucher')},
            },
        ),
        migrations.CreateModel(
            name='VoucherRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_role', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_only', models.BooleanField(default=False)),
                ('min_order_amount', models.FloatField(default=0)),
                ('min_items', models.IntegerField(default=0)),
                ('period_type', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('discount_amount', models.FloatField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.uservoucher')),
            ],
        ),
    ]
