# Generated by Django 5.1.7 on 2026-02-24 16:49

import vouchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucher_release_date_voucherdistributionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherrule',
            name='required_product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=vouchers.models.generate_unique_voucher_code, max_length=50, unique=True),
        ),
    ]
