# Generated by Django 5.1.7 on 2026-03-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucherrule_required_product_type_alter_voucher_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(default='order_success', max_length=50)),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('skipped', 'Skipped')], default='processed', max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
