# Generated by Django 4.2.29 on 2026-03-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucherdeliverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
