# Generated by Django 4.2.29 on 2026-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_voucher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
