# Generated by Django 4.2.29 on 2026-03-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_voucher_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
