# Generated by Django 5.1.7 on 2026-04-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_voucher_max_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherrule',
            name='lookback_days',
            field=models.IntegerField(default=0, help_text='Số ngày tính ngược từ hiện tại (ví dụ: 30 ngày qua). Bị bỏ qua nếu có target_month/year'),
        ),
        migrations.AddField(
            model_name='voucherrule',
            name='min_accumulated_orders',
            field=models.IntegerField(default=0, help_text='Tổng số đơn hàng thành công tối thiểu để được nhận mã'),
        ),
        migrations.AddField(
            model_name='voucherrule',
            name='min_accumulated_spent',
            field=models.FloatField(default=0, help_text='Tổng số tiền tối thiểu user phải từng tiêu để được nhận mã'),
        ),
        migrations.AddField(
            model_name='voucherrule',
            name='target_month',
            field=models.IntegerField(blank=True, help_text='Tháng cụ thể (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='voucherrule',
            name='target_year',
            field=models.IntegerField(blank=True, help_text='Năm cụ thể (ví dụ: 2025)', null=True),
        ),
    ]
