# Generated by Django 4.2.29 on 2026-04-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_voucher_max_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdeliverylog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucherdeliverylog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped_no_email', 'Skipped No Email'), ('skipped_no_phone', 'Skipped No Phone')], max_length=30),
        ),
    ]
