# Generated by Django 5.1.7 on 2026-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
