# Generated by Django 5.1.7 on 2026-03-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="external_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid"), ("canceled", "Canceled")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
