# Generated by Django 5.1.7 on 2026-04-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_external_order_id_order_status'),
        ('vouchers', '0009_voucherrule_lookback_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
